// examples/vue/basic-code-editor/src/App.vue
<script lang="ts" setup>
import { CodeEditor, useCodeEditorState } from "@codewrapper/vue";

const { ref, value } = useCodeEditorState("<div>Test</div>\n\nTesting");
const setValue = (e: Event) => {
  value.value = (e.target as HTMLInputElement).value;
};
</script>

<template>
  <h2>Base CodeMirror Editor</h2>
  <CodeEditor :ref="ref" />
  <h2>Vue Projected Value</h2>
  <pre>{{ value }}</pre>
  <h2>Vue setValue Usage</h2>
  <textarea :value="value" @input="setValue($event)" />
</template>

// examples/react/src/App.tsx
import * as React from "react";
import { Container, useContainerState } from "@codewrapper/react";

export default function App() {
  const [value, setValue, stateRef] = useContainerState(
    "<div>Test</div>\n\nTesting",
  );

  return (
    <div>
      <h2>Base CodeMirror Editor</h2>
      <Container ref={stateRef} />
      <h2>React Projected Value</h2>
      <pre>{value}</pre>
      <h2>React setValue Usage</h2>
      <textarea value={value} onChange={(e) => setValue(e.target.value)} />
    </div>
  );
}
