// packages/vue/src/CodeEditor.vue
<script setup lang="ts">
import { onUnmounted, shallowRef } from "vue";
// import { CodeEditor as CodeEditorBase } from "@codewrapper/templating-base/vue";
import { setCodeEditorElement, getCodeEditorState } from "@codewrapper/core";
import { EditorView } from "@codemirror/view";

const view = shallowRef<EditorView>();
const callback = (el: HTMLElement) => {
  if (!el) {
    return;
  }
  view.value = setCodeEditorElement(el as HTMLElement, getCodeEditorState());
};

onUnmounted(() => {
  if (view.value) {
    view.value.destroy();
  }
});

defineExpose({ view });
</script>

<template>
  <div :ref="callback as never" />
  <!--  <CodeEditorBase :elRef="callback" />-->
</template>

// packages/react/src/CodeEditor.tsx
import { CodeEditor as CodeEditorBase } from "@codewrapper/templating-base/react";
import { getCodeEditorState, setCodeEditorElement } from "@codewrapper/core";
import {
  ForwardedRef,
  forwardRef,
  useCallback,
  useLayoutEffect,
  useState,
} from "react";
import type { EditorView } from "@codemirror/view";

function assignRef<T>(ref: ForwardedRef<T>, value: T) {
  if (typeof ref === "function") {
    ref(value);
  } else if (ref) {
    ref.current = value;
  }
}

export const CodeEditor = forwardRef<EditorView>((_, ref) => {
  const [containerEl, setContainerEl] = useState<HTMLElement>();

  useLayoutEffect(() => {
    if (!containerEl) return;
    const view = setCodeEditorElement(containerEl, getCodeEditorState());
    if (ref) assignRef(ref, view);
    return () => {
      view.destroy();
    };
  }, [containerEl]);

  return (
    <CodeEditorBase
      ref={useCallback((view: HTMLElement) => setContainerEl(view), [])}
    />
  );
});
