// packages/vue/src/Container.vue
<script setup lang="ts">
import { VNodeRef } from "vue";
import {Container as ContainerBase} from "@mitosis.template/templating-base/vue";
import { setElement } from "@mitosis.template/core";

const callback: VNodeRef = (el) => setElement(el as HTMLElement)
</script>

<template>
  <ContainerBase :ref="callback"/>
</template>

// packages/react/src/Container.tsx
import { Container as ContainerBase } from "@mitosis.template/templating-base/react";
import { setElement } from "@mitosis.template/core";

export const Container = () => {
  const callback = (el: HTMLElement) => {
    if (!el) return;
    setElement(el);
  };
  return <ContainerBase ref={callback} />;
};
