// packages/vue/src/Terminal.vue
<script setup lang="ts">
import { onUnmounted, shallowRef } from "vue";
// import { Terminal as TerminalBase } from "@codewrapper/templating-base/vue";
import { initTerm } from "@codewrapper/core";
import { Terminal as XTermTerminal } from "@xterm/xterm";

const term = shallowRef<XTermTerminal>();
const callback = (el: HTMLElement) => {
  if (!el) {
    return;
  }
  const localTerm = initTerm();
  localTerm.open(el);
  term.value = localTerm;
};

onUnmounted(() => {
  if (term.value) {
    term.value.dispose();
  }
});

defineExpose({ term });
</script>

<template>
  <div :ref="callback as never" />
  <!--  <TerminalBase :elRef="callback" />-->
</template>

// packages/react/src/Terminal.tsx
import { Terminal as TerminalBase } from "@codewrapper/templating-base/react";
import { initTerm } from "@codewrapper/core";
import { forwardRef, useCallback, useLayoutEffect, useState } from "react";
import { assignRef } from "./utils";
import { Terminal as XTermTerminal } from "@xterm/xterm";

export const Terminal = forwardRef<XTermTerminal>((_, ref) => {
  const [containerEl, setContainerEl] = useState<HTMLElement>();

  useLayoutEffect(() => {
    if (!containerEl) return;
    const term = initTerm();
    if (ref) assignRef(ref, term);
    term.open(containerEl);
    return () => {
      term.dispose();
    };
  }, [containerEl]);

  return (
    <TerminalBase
      ref={useCallback((view: HTMLElement) => setContainerEl(view), [])}
    />
  );
});
